spring.application.name=Planificador
spring.datasource.url=jdbc:mysql://localhost:3306/Planner
spring.datasource.username=root
spring.datasource.password=equilibrha123

spring.jpa.hibernate.ddl-auto=update
spring.jp.show-sql=true